config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'home', to: 'pages#home'
  resources :developers, only: %i[create index new show edit update] do
    resources :bookings, only: :create
  end
  resources :bookings, only: %i[index destroy]
  get 'bookings/:id/accept', to: 'bookings#accept', as: 'accept'
  delete 'bookings/:id/reject', to: 'bookings#reject', as: 'reject'
  resources :contacts, only: %i[create new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :developer

  validates :job, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, validate: true
  attribute :nickname, captcha: true


  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "patriciopherrero@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/developer.rb
class Developer < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :description, :first_name, :last_name, :address, :photo, presence: true
  validates :description, length: { maximum: 200 }
    include PgSearch::Model
    pg_search_scope :search_by_language,
    against: %i[language],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :developer
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def authorize_admin
    redirect_to :back, status: 401 unless current_user.admin
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @developer = Developer.find_by(user_id: current_user.id)
    @bookings = Booking.where(user_id: current_user.id)
    if @developer
      @booked = Booking.where(developer_id: @developer.id).where(status: false)
      @accepted = Booking.where(developer_id: @developer.id).where(status: true)
    end
  end

  def accept
    booking = Booking.find(params[:id])
    booking.status = true
    booking.save

    redirect_to bookings_path
  end

  def reject
    booking = Booking.find(params[:id])
    booking.destroy

    redirect_to bookings_path
  end

  def create
    @booking = Booking.new(bookings_params)
    @developer = Developer.find(params[:developer_id])
    @booking.developer = @developer
    @booking.user = current_user
    @booking.save

    redirect_to bookings_path
  end

  def destroy; end

  def bookings_params
    params.require(:booking).permit(:job)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "language ILIKE :query"
      @developers = Developer.where(sql_query, query: "%#{params[:query]}%")
    else
      @developers = Developer.all
    end
    if current_user
      if @developers.find_by(user_id: current_user.id)
        @mydev = @developers.find_by(user_id: current_user.id)
      end
    end
  end

  def show
    if current_user
      @booking = Booking.new
      @developer = Developer.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def new
    if current_user
      @developer = Developer.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @developer = Developer.new(developers_params)
    @developer.user = current_user
    @developer.language = params[:language]
    if @developer.save
      redirect_to developers_path
    else
      render :new
    end
  end

  def edit
    @developer = Developer.find(params[:id])
  end

  def update
    @developer = Developer.find(params[:id])
    @developer.update(developers_params)
  end

  private

  def developers_params
    params.require(:developer).permit(:rating, :description, :first_name, :last_name, :language, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/accept.html.erb
<h1>Bookings#accept</h1>
<p>Find me in app/views/bookings/accept.html.erb</p>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row justify-content-around">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <h3 class='booking'>Requests</h3>
      <div class="d-flex flex-column">
        <% @bookings.each do |b| %>
          <li class='card book d-flex flex-row justify-content-between request'>
            <div>
              <b>Developer: </b><%= b.developer.first_name %> <%= b.developer.last_name %> <br><b>Project: </b><%= b.job %>
              </div>
              <div class="align-self-center status">
              <% if b.status == true %>
                ✅
                <% else %>
                🕒
              <% end %>
            </div>
          </li>
        <% end %>
      </div>
    </div>
  <% if @developer %>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <h3 class='booking'>My Bookings</h3>
      <div class="d-flex flex-column">
        <% @booked.each do |b| %>
          <li class='card book'><b>e-mail: </b><%= b.user.email %> <br><b>Project: </b> <%= b.job %> <br> <div class='d-flex'><%= link_to 'Accept', accept_path(b), class: "btn btn-accept" %> <%= link_to "Reject", reject_path(b),method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-reject" %></div></li>
        <% end %>
      </div>
    </div>
    <br>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <h3 class='accepted'>Accepted</h3>
      <div class="accepted d-flex flex-column">
        <% @accepted.each do |b| %>
        <li class='card book'><b>e-mail: </b><%= b.user.email %> <br> <b>Project: </b> <%= b.job %></li>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/reject.html.erb
<h1>Bookings#reject</h1>
<p>Find me in app/views/bookings/reject.html.erb</p>

app/views/contacts/create.html.erb
<div class="mail-container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/new.html.erb
<div class="mail-container">
  <h1>Contact Form</h1>
  <%= form_for @contact do |f| %>
    <div class="col-md-6">
      <%= f.label :name %><br>
      <%= f.text_field  :name, required: true, class: "contact-form-text-area" %><br>

      <%= f.label :email %><br>
      <%= f.text_field :email, required: true, class: "contact-form-text-area" %><br>

      <%= f.label :message %><br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
            placeholder: "Send me a message"%><br>

      <div class= "d-none">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>

      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/developers/create.html.erb
<h1>Developers#create</h1>
<p>Find me in app/views/developers/create.html.erb</p>

app/views/developers/edit.html.erb
<%= form_for(@developer) do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/developers/index.html.erb
<div class="index-container">
	<div class="title-bar"><span class="title">${developer.all} — bash — 80x<span class="terminal-height">10</span></span></div>
        <%= form_tag developers_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "$ Find the programming language you need",
            style: "height: 46px;"
          %>
</div>
  <div class="btn-container">
    <%= submit_tag "Search", class: "btn btn-outline-dark btn-sm btn-block" %>
  </div>
    <% end %>



   <div class="row justify-content-center">
   <% if @mydev == nil %>
    <div class="col-xl-3 col-sm-6 mb-3 flip-card border">
      <div class="flip-card-inner my-card">
        <div class="flip-card-front d-flex flex-column justify-content-around align-items-center shadow-sm rounded">
          <img src="https://pbs.twimg.com/profile_images/1220073059467583496/y2rLoig5_400x400.jpg" alt="" width="100" class="rounded-circle">
          <b><h5 class="mb-0">Become a developer</h5></b><span class="small text-uppercase text-muted">Expert in: _____<br> your-email@you.com </span>
          <ul class="list-inline">
            <li class="list-inline-item"><i class="fas fa-star"></i></li>
          </ul>
        </div>
        <div class="flip-card-back d-flex flex-column justify-content-between rounded">
          <h2 class='b-back'>Apply today!</h2>
          <span class="small text-uppercase text-muted">Become a developer in one easy step. Apply today and change your life.</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>
          </ul>
          <%= link_to '$ Developer.new', new_developer_path, class: 'btn btn-primary hire-btn' %>
        </div>
      </div>
    </div>
    <% else %>
            <div class="col-xl-3 col-sm-6 mb-3 flip-card border">
            <div class="flip-card-inner main-card">
              <div class="flip-card-front d-flex flex-column justify-content-around align-items-center shadow-sm rounded">
              <%= image_tag @mydev.photo, class: "rounded-circle" %>
                <h5 class="mb-0"><%= @mydev.first_name %></h5><span class="small text-uppercase text-muted">Expert in: <em><%= @mydev.language %></em><br> <%= @mydev.user.email %> </span>
                <% rating = @mydev.rating.to_i %>
                <ul class="list-inline">
                  <% rating.times do %>
                    <li class="list-inline-item"></li><i class="fas fa-star"></i></li>
                  <% end %>
                </ul>
            </div>
            <div class="flip-card-back d-flex flex-column justify-content-between rounded">
              <h2 class='b-back'>My Account</h2>
              <span class="small text-uppercase text-muted"><%= @mydev.description %></span>
              <ul class="social mb-0 list-inline mt-3">
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>
              </ul>
              <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-primary hire-btn unround' %>
              <%= link_to 'My Bookings', bookings_path, class: 'btn btn-primary hire-btn' %>
            </div>
          </div>
        </div>
  <% end %>
      <% @developers.each do |d| %>
      <% next if d.user == current_user %>
        <div class="col-xl-3 col-sm-6 mb-3 flip-card border">
            <div class="flip-card-inner">
              <div class="flip-card-front d-flex flex-column justify-content-around align-items-center shadow-sm rounded">
              <%= image_tag d.photo, class: "rounded-circle" %>
                <h5 class="mb-0"><%= d.first_name %></h5><span class="small text-uppercase text-muted">Expert in: <em><%= d.language %></em><br> <%= d.user.email %> </span>
                <% rating = d.rating.to_i %>
                <ul class="list-inline">
                  <% rating.times do %>
                    <li class="list-inline-item"></li><i class="fas fa-star"></i></li>
                  <% end %>
                </ul>
            </div>
            <div class="flip-card-back d-flex flex-column justify-content-between rounded">
              <h2 class='pt-3 b-back'>Why me?</h2>
                <span class="small text-uppercase text-muted overflow-auto" id="description"><%= d.description %></span>
              <ul class="social mb-0 list-inline mt-3">
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>
              </ul>
              <%= link_to 'Hire', developer_path(d), class: 'btn btn-primary rounded-bottom hire-btn' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/developers/new.html.erb
<div class="bigg-container">
  <div class="sign-container-dev">
  <span class="login-logo-dev">
    <i class="fas fa-code"></i>
  </span>
    <%= simple_form_for @developer do |f| %>
    <fieldset>
    <legend><span class="number"></span> < developer info ></legend>
    <%= f.input :first_name, placeholder:"< your first name >", label: "first-name - bash - 80x10" %>
    <%= f.input :last_name, placeholder:"< your last name >", label: "last-name - bash - 80x10" %>
    <%= f.input :description, as: :text, placeholder:"< about yourself, special skills, your hourly rate >", label: "description - bash - 80x10" %>
    <div class="languages">
    <label for="language">preffered programming languages</label>
    <select id="language" name="language">
    <optgroup>
      <option value="javascript">JavaScript</option>
      <option value="php">PHP</option>
      <option value="java">Java</option>
      <option value="golang">Golang</option>
      <option value="python">Python</option>
      <option value="c#">C#</option>
      <option value="C++">C++</option>
      <option value="erlang">Erlang</option>
      <option value="ruby">Ruby</option>
    </optgroup>
    </select>
    </fieldset>
    <fieldset>
    <legend><span class="number"></span> < additional info ></legend>
    <%= f.input :address, placeholder:"< your address >", label: "address - bash - 80x10" %>
    <%= f.file_field :photo, placeholder:"Profile picture URL *", label: false, class: "input-photo" %>
    </fieldset>
    <div class="bootun">
    <%= f.submit :submit, class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/developers/show.html.erb
<div class="row py-5 px-4 back">
  <div class="col-md-5 mx-auto"> <!-- Profile widget -->
    <div class="bg-white shadow rounded overflow-hidden">
      <div class="px-4 pt-0 pb-4 cover">
        <div class="media align-items-end profile-head d-flex">
          <div class="profile mr-3">
            <%= image_tag(@developer.photo, class: [:rounded, "mb-2", "img-thumbnail", :width]) %>
              <div class="media-body mb-5 text-white">
                <h4 class="mt-0 mb-0"><%= @developer.first_name %> <%= @developer.last_name %></h4>
                <p class="small mb-4">
                <i class="fas fa-map-marker-alt mr-2 pb-4"></i> <%= @developer.address %></p>
              </div>
            </div>
            </div>
          </div>
          <div class="bg-light p-4 d-flex justify-content-center text-center">
            <ul class="list-inline mb-0">
              <li class="list-inline-item">
                <h5 class="font-weight-bold mb-0 d-block">215</h5>
                <small class="text-muted">
                <i class="mr-1"></i>Projects</small> </li>
                <li class="list-inline-item">
                <h5 class="font-weight-bold mb-0 d-block">745</h5>
                <small class="text-muted"> <i class="mr-1"></i>Followers</small></li>
                <li class="list-inline-item">
                <h5 class="font-weight-bold mb-0 d-block"><%= @developer.rating %></h5>
                <small class="text-muted">
                <i class="mr-1"></i>Rating</small>
              </li>
              </ul>
          </div>
          <div class="about-hdr">
            <div class="px-4 py-3 radius">
			        <div class="hdr"><span class="title">about-me — bash — 80x<span class="terminal-height">10</span></span></div>
                <div class="about-main p-4 overflow-auto">
                   <span class="element2"></span><span class="typed-cursor"></span>
                   <br>
                      <p class="element2 hidden"> web developer, expert in: <%= @developer.language %></p>
                      <p class="element2 hidden">lives in: <%= @developer.address %></p>
                      <p class="element2 hidden"><%= @developer.user.email %></p>
                      <p class="element2 hidden"><%= @developer.description %></p>
                </div>
            </div>
          </div>
          <div class="py-4 px-4">
            <div class="d-flex align-items-center justify-content-between mb-3">
            <h5 class="mb-0">Recent projects</h5>
            <a href="#" class="btn btn-link text-muted">Show all</a>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 mb-2 pr-lg-1">
              <img src="https://cdn.dribbble.com/users/6234/screenshots/17430129/media/604770912834878b021248a226c51f60.png?compress=1&resize=1200x900&vertical=top" alt="" class="img-fluid rounded shadow-sm">
            </div>
            <div class="col-lg-6 col-md-6 mb-2 pl-lg-1">
              <img src="https://cdn.dribbble.com/users/6234/screenshots/17414052/media/d0144931ecf137ec49677dfff5fcd161.png?compress=1&resize=1200x900&vertical=top" alt="" class="img-fluid rounded shadow-sm">
            </div>
            <div class="col-lg-6 col-md-6 pr-lg-1 mb-2">
              <img src="https://cdn.dribbble.com/users/6234/screenshots/17396277/media/8119a1bd3b5784b7acc868fa09df1c38.png?compress=1&resize=1200x900&vertical=top" alt="" class="img-fluid rounded shadow-sm">
            </div>
            <div class="col-lg-6 col-md-6 pl-lg-1">
              <img src="https://cdn.dribbble.com/users/6234/screenshots/16843254/media/16daa34ccde6dd68d699264d205c6487.png?compress=1&resize=1200x900&vertical=top" alt="" class="img-fluid rounded shadow-sm">
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class='form'>
        <%= simple_form_for [@developer, @booking] do |f| %>
        <%= f.input :job, :as => :text, label: 'describe-the-work-you-want — bash — 80x' %>
        <%= f.submit :book , class: 'btn btn-outline-dark btn-sm btn-block'%>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A-rented-development</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Raleway:wght@100&family=Space+Mono&display=swap" rel="stylesheet">
  </head>

  <div class="main-container">
    <body>
      <%= render 'shared/navbar' %>
      <div style="min-height: calc(100vh - 300px)">
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
    </body>
  </div>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="header1">
      <h1>< Get the right <%= link_to 'developers' do  %><span class="diff">developer</span><% end %> for you today ></h1>
  </div>
  <div>
    <div class="head-wrap shift-text">
		    <div class="text-editor-wrap">
			    <div class="title-bar"><span class="title">typed.js — bash — 80x<span class="terminal-height">10</span></span></div>
			      <div class="text-body">
				     $ <span class="element"></span><span class="typed-cursor"></span>
			      </div>
		      </div>
          <%# <button type="button" class="btn btn-dark">Find your developer here!</button> %>
	    </div>
    </div>
</div>

app/views/pages/sign_in.html.erb
<div class="wrap-login100">
  <form class="login100-form validate-form">
    <span class="login100-form-logo">
      <i class="zmdi zmdi-landscape"></i>
    </span>
    <span class="login100-form-title p-b-34 p-t-27">
      < log in >
    </span>
  <div class="wrap-input100 validate-input login-text" data-validate="Enter username">
    <input class="input100 placeholder" type="text" name="username" placeholder="Username">
      <span class="focus-input100" data-placeholder=""></span>
  </div>
  <div class="wrap-input100 validate-input login-text" data-validate="Enter password">
    <input class="input100 placeholder" type="password" name="pass" placeholder="Password">
    <span class="focus-input100" data-placeholder=""></span>
  </div>
  <div class="contact100-form-checkbox">
    <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
      <label class="label-checkbox100" for="ckb1">
      Remember me
      </label>
    </div>
  <div class="container-login100-form-btn">
    <button class="login100-form-btn">
    Login
    </button>
  </div>
  <div class="text-center p-t-90">
    <a class="txt1" href="#">
    Forgot Password?
    </a>
  </div>
  </form>
</div>

app/views/shared/_background.html.erb
<%# <%= image_tag ("back.png") %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <h3>< A-Rented-Development /></h3>
    <p>A-rented-development is a website made with <i class="far fa-heart"></i> by three geeks</p>
    <p>< Luisi > < Nacho > < Pato ></p>
  <div class="logos">
     <ul class="socials">
      <li><a href="#"><i class="fab fa-facebook"></i></a></li>
      <li><a href="#"><i class="fab fa-twitter"></i></a></li>
      <li><a href="#"><i class="fab fa-google-plus"></i></a></li>
      <li><a href="#"><i class="fab fa-youtube"></i></a></li>
      <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
    </ul>
  </div>
</div>
  <div class="footer-bottom">
    <p>Copyright ©2022 <span class='team'>Gasho Team</span></p>
  </div>
  <div class="footer-menu">
    <ul class="f-menu">
        <li><%= link_to '/home' do %> Home <% end %></li>
        <li><a href="https://pbs.twimg.com/profile_images/1220073059467583496/y2rLoig5_400x400.jpg">About</a></li>
        <li><%= link_to new_contact_path do %> Contact Us <% end %></li>
        <li><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Secret Gem</a></li>
    </ul>
  </div>
</div>

app/views/shared/_form-control.html.erb
<div class="wrap-login100">
  <form class="login100-form validate-form">
    <span class="login100-form-logo">
      <i class="zmdi zmdi-landscape"></i>
    </span>
    <span class="login100-form-title p-b-34 p-t-27">
      < log in >
    </span>
  <div class="wrap-input100 validate-input" data-validate="Enter username">
    <input class="input100" type="text" name="username" placeholder="Username">
      <span class="focus-input100" data-placeholder=""></span>
  </div>
  <div class="wrap-input100 validate-input" data-validate="Enter password">
    <input class="input100" type="password" name="pass" placeholder="Password">
    <span class="focus-input100" data-placeholder=""></span>
  </div>
  <div class="contact100-form-checkbox">
    <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
      <label class="label-checkbox100" for="ckb1">
      Remember me
      </label>
    </div>
  <div class="container-login100-form-btn">
    <button class="login100-form-btn">
    Login
    </button>
  </div>
  <div class="text-center p-t-90">
    <a class="txt1" href="#">
    Forgot Password?
    </a>
  </div>
  </form>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/home", class: "navbar-brand" do %>
      <%= image_tag "https://i.pinimg.com/originals/bc/ce/f3/bccef3acf376bba141d56eb0d8fcfc09.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if current_user.developer.nil? %>
            <%= image_tag "https://pbs.twimg.com/profile_images/1220073059467583496/y2rLoig5_400x400.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li class="nav-item dropdown">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
              <li class="nav-item dropdown">
                <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              </li>
            </div>
          <% else %>
          <li class="nav-item dropdown">
            <%= image_tag current_user.developer.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", developer_path(Developer.find_by(user_id: current_user.id)), class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%# asd %>